import { HighlandsEvent } from "./model";

export const events: HighlandsEvent[] = [
  {
    id: 0,
    name: '21 Days of Prayer and Feasting',
    beginDate: new Date('2026-01-04'),
    endDate: new Date('2026-01-25'),
    description: "Pray First.",
    cost: 0,
    isPublished: false,
  },{
    id: 1,
    name: 'Marriage Conference',
    beginDate: new Date('2026-02-20'),
    endDate: new Date('2026-02-21'),
    description: "Grow together in marriage purposefully.",
    cost: 140,
    isPublished: false,
  },
  {
    id: 2,
    name: 'Freedom Conference',
    beginDate: new Date('2026-04-17'),
    endDate: new Date('2026-04-18'),
    description: "Learning to live in freedom everyday.",
    cost: 0,
    isPublished: true,
  },
  {
    id: 3,
    name: 'Summer Blast',
    beginDate: new Date('2026-06-22'),
    endDate: new Date('2026-06-24'),
    description: "Highlands Kids' opportunity to grow in faith and friendship.",
    cost: 0,
    isPublished: true,
  },
  {
    id: 4,
    name: 'Serve Day',
    beginDate: new Date('2026-07-11'),
    endDate: new Date('2026-07-11'),
    description: "Highlands' opportunity to serve their city.",
    cost: 0,
    isPublished: true,
  },
  {
    id: 5,
    name: 'Motion Conference',
    beginDate: new Date('2026-07-23'),
    endDate: new Date('2026-07-25'),
    description: "Highlands Students' opportunity to get refreshed, equipped, and inspired to live their lives in MOTION.",
    cost: 135,
    isPublished: true,
  },
  {
    id: 6,
    name: '21 Days of Prayer and Fasting',
    beginDate: new Date('2026-08-02'),
    endDate: new Date('2026-08-22'),
    description: "Pray First.",
    cost: 0,
    isPublished: true,
  },
];