import { HighlandsEvent } from "./model";

export const events: HighlandsEvent[] = [
  {
    id: '0',
    title: '21 Days of Prayer and Feasting',
    description: "Pray First.",
    cost: 0,
    campus: "Grants Mill",
    category: "All",
    isPublished: false,
    startDateTime: new Date('2026-01-04'),
    endDateTime: new Date('2026-01-25'),
  },
  {
    id: '1',
    title: 'Marriage Conference',
    description: "Grow together in marriage purposefully.",
    cost: 140,
    campus: "Grants Mill",
    category: "Married Couples",
    isPublished: false,
    startDateTime: new Date('2026-02-20'),
    endDateTime: new Date('2026-02-21'),
  },
  {
    id: '2',
    title: 'Freedom Conference',
    description: "Learning to live in freedom everyday.",
    cost: 0,
    campus: "Grants Mill",
    category: "All",
    isPublished: true,
    startDateTime: new Date('2026-04-17'),
    endDateTime: new Date('2026-04-18'),
  },
  {
    id: '3',
    title: 'Summer Blast',
    description: "Highlands Kids' opportunity to grow in faith and friendship.",
    cost: 0,
    campus: "Grants Mill",
    category: "Highlands Kids",
    isPublished: true,
    startDateTime: new Date('2026-06-22'),
    endDateTime: new Date('2026-06-24'),
  },
  {
    id: '4',
    title: 'Serve Day',
    description: "Highlands' opportunity to serve their city.",
    cost: 0,
    campus: "Grants Mill",
    category: "All",
    isPublished: true,
    startDateTime: new Date('2026-07-11'),
    endDateTime: new Date('2026-07-11'),
  },
  {
    id: '5',
    title: 'Motion Conference',
    description: "Highlands Students' opportunity to get refreshed, equipped, and inspired to live their lives in MOTION.",
    cost: 135,
    campus: "Grants Mill",
    category: "Highlands Students",
    isPublished: true,
    startDateTime: new Date('2026-07-23'),
    endDateTime: new Date('2026-07-25'),
  },
  {
    id: '6',
    title: '21 Days of Prayer and Fasting',
    description: "Pray First.",
    cost: 0,
    campus: "Grants Mill",
    category: "All",
    isPublished: true,
    startDateTime: new Date('2026-08-02'),
    endDateTime: new Date('2026-08-22'),
  },
];